// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_7UKfd5xzoVar-VlInydjoxFlMTaJ2Hg',
    appId: '1:885549030308:web:f560f80d9b44ecc1e97f31',
    messagingSenderId: '885549030308',
    projectId: 'world-wide-connect-3b5f2',
    authDomain: 'world-wide-connect-3b5f2.firebaseapp.com',
    storageBucket: 'world-wide-connect-3b5f2.firebasestorage.app',
    measurementId: 'G-YX7FCL9550',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe1kqFTHG4NQsbKW8G5lszgHzyufFq2sM',
    appId: '1:885549030308:android:ba5bc845bfc8956ce97f31',
    messagingSenderId: '885549030308',
    projectId: 'world-wide-connect-3b5f2',
    storageBucket: 'world-wide-connect-3b5f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALzSnUtczC3gB9UwU3HRYPrH7Sjoggss8',
    appId: '1:885549030308:ios:db0588d6c53b8226e97f31',
    messagingSenderId: '885549030308',
    projectId: 'world-wide-connect-3b5f2',
    storageBucket: 'world-wide-connect-3b5f2.firebasestorage.app',
    iosBundleId: 'com.example.wwc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALzSnUtczC3gB9UwU3HRYPrH7Sjoggss8',
    appId: '1:885549030308:ios:db0588d6c53b8226e97f31',
    messagingSenderId: '885549030308',
    projectId: 'world-wide-connect-3b5f2',
    storageBucket: 'world-wide-connect-3b5f2.firebasestorage.app',
    iosBundleId: 'com.example.wwc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_7UKfd5xzoVar-VlInydjoxFlMTaJ2Hg',
    appId: '1:885549030308:web:82fb96100a99acb2e97f31',
    messagingSenderId: '885549030308',
    projectId: 'world-wide-connect-3b5f2',
    authDomain: 'world-wide-connect-3b5f2.firebaseapp.com',
    storageBucket: 'world-wide-connect-3b5f2.firebasestorage.app',
    measurementId: 'G-9RJJV35BE8',
  );

}